### ISSUE TITLE
No support for Chrysler

### ISSUE THREAD

**Issue by Wetzel402** [wubbl0rz/FiatChamp#66]
There is no option for Chrysler.  If I have some leads as to how to reverse engineer I could fork and add the relevant api information.

**Comment by Blueion76** [comment]
@Wetzel402 create an issue in my fork and i'll look into it: https://github.com/Blueion76/FCAUconnect-HA

**Comment by Blueion76** [comment]
@Wetzel402 Update: I've added Chrysler support, just need it to be tested.

**Comment by ckevac** [comment]
I am trying to test Chrysler but it is not working.  There is no "Chrysler" in the Add-On config.  Is there a certain make I should try?

**Comment by Blueion76** [comment]
> I am trying to test Chrysler but it is not working.  There is no "Chrysler" in the Add-On config.  Is there a certain make I should try?

Seems to be showing up for me. Maybe try uninstalling and reinstalling the addon? ![image](https://github.com/user-attachments/assets/365814ad-d80f-47c1-8fad-8bfbd4631c93)

**Comment by ckevac** [comment]
That worked. Thanks. I still can't get it to connect to my account but I think the issue is my account.  I'm getting this error in the logs:

[20:42:37 ERR] System.Exception: Authentication failed. 403120 Forbidden Account Temporarily Locked Out
   at FiatResponse.ThrowOnError(String message) in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/FiatResponse.cs:line 31
   at FCAUconnect.FiatClient.Login() in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/FiatClient.cs:line 481
   at FCAUconnect.FiatClient.LoginAndKeepSessionAlive() in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/FiatClient.cs:line 429
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/Program.cs:line 72
[20:42:37 INF] Fetching COMPLETED. Next update in 2 minutes.

**Comment by Wetzel402** [comment]
I run HA core so it might take me a minute to test.  I have to spin up containers for your add-on and a MQTT broker.

**Comment by Blueion76** [comment]
> That worked. Thanks. I still can't get it to connect to my account but I think the issue is my account.  I'm getting this error in the logs:
> 
> 
> 
> [20:42:37 ERR] System.Exception: Authentication failed. 403120 Forbidden Account Temporarily Locked Out
> 
>    at FiatResponse.ThrowOnError(String message) in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/FiatResponse.cs:line 31
> 
>    at FCAUconnect.FiatClient.Login() in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/FiatClient.cs:line 481
> 
>    at FCAUconnect.FiatClient.LoginAndKeepSessionAlive() in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/FiatClient.cs:line 429
> 
>    at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in /home/runner/work/FCAUconnect-HA/FCAUconnect-HA/FCAAddon/FCAClient/Program.cs:line 72
> 
> [20:42:37 INF] Fetching COMPLETED. Next update in 2 minutes.
> 
> 

Are you in the US, or are you located somewhere else? I only implemented support for US Chrysler so far.

**Comment by ckevac** [comment]
I'm in Canada. I guess that's why?

**Comment by Blueion76** [comment]
> I'm in Canada. I guess that's why?

Ah, ok then. I'll try to add an option for Canada and the appropriate endpoints to the code sometime in the next couple of days. I'll let you know when it's ready, apologies.

**Comment by ckevac** [comment]
That would be awesome!  Thank you!

**Comment by Blueion76** [comment]
> That would be awesome! Thank you!

Just added support for Canada/Asia accounts, give it a try when you have a chance :)

**Comment by Wetzel402** [comment]
Do you know what port I need to map the container to?

Edit: I tried spinning up the container with a very basic configuration and I see it is looping
```
services:
  uconnect:
    image: ghcr.io/blueion76/image-amd64-fca-uconnect:latest 
    container_name: uconnect
    restart: always
    ports:
        - "6969:6969" 
    volumes:
      - /share/ContainerStation/home-assistant/:/app/data
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
```

**Comment by Blueion76** [comment]
> Do you know what port I need to map the container to?
> 
> Edit: I tried spinning up the container with a very basic configuration and I see it is looping
> 
> ```
> services:
>   uconnect:
>     image: ghcr.io/blueion76/image-amd64-fca-uconnect:latest 
>     container_name: uconnect
>     restart: always
>     ports:
>         - "6969:6969" 
>     volumes:
>       - /share/ContainerStation/home-assistant/:/app/data
>     environment:
>       PUID: 1000
>       PGID: 1000
>       TZ: America/Chicago
> ```

Look at the example here: https://github.com/Blueion76/FCAUconnect-HA/tree/master?tab=readme-ov-file#standalone-docker-container

Just tested this with my account and it seems to work fine.

**Comment by ckevac** [comment]
I think we have progress but I am getting a new error now.

"ErrorCode": 0,
  "ErrorDetails": null,
  "ErrorMessage": null,
  "ApiVersion": 2,
  "StatusCode": 200,
  "StatusReason": "OK",
  "Time": "2024-12-10T21:50:47.711+00:00"
}
[16:50:47 WRN] Error connecting to https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token. Result: Forbidden. Retrying in 00:00:01
[16:50:48 WRN] Error connecting to https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token. Result: Forbidden. Retrying in 00:00:02
[16:50:51 WRN] Error connecting to https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token. Result: Forbidden. Retrying in 00:00:05
[16:50:56 WRN] Error connecting to the FCA API. 
This can happen from time to time. Retrying in 2 minutes.
[16:50:56 DBG] ERROR: Call failed with status code 403 (Forbidden): POST https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token
[16:50:56 DBG] STATUS: 403
[16:50:56 DBG] RESPONSE: {"name":"INVALID_AUTH_SITE","message":"The authentication site is invalid"}
[16:50:56 INF] Fetching COMPLETED. Next update in 2 minutes.

I really appreciate your help with this!

**Comment by Blueion76** [comment]
> I think we have progress but I am getting a new error now.
> 
> 
> 
> "ErrorCode": 0,
> 
>   "ErrorDetails": null,
> 
>   "ErrorMessage": null,
> 
>   "ApiVersion": 2,
> 
>   "StatusCode": 200,
> 
>   "StatusReason": "OK",
> 
>   "Time": "2024-12-10T21:50:47.711+00:00"
> 
> }
> 
> [16:50:47 WRN] Error connecting to https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token. Result: Forbidden. Retrying in 00:00:01
> 
> [16:50:48 WRN] Error connecting to https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token. Result: Forbidden. Retrying in 00:00:02
> 
> [16:50:51 WRN] Error connecting to https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token. Result: Forbidden. Retrying in 00:00:05
> 
> [16:50:56 WRN] Error connecting to the FCA API. 
> 
> This can happen from time to time. Retrying in 2 minutes.
> 
> [16:50:56 DBG] ERROR: Call failed with status code 403 (Forbidden): POST https://authz.sdpr-02.fcagcv.com/v2/cognito/identity/token
> 
> [16:50:56 DBG] STATUS: 403
> 
> [16:50:56 DBG] RESPONSE: {"name":"INVALID_AUTH_SITE","message":"The authentication site is invalid"}
> 
> [16:50:56 INF] Fetching COMPLETED. Next update in 2 minutes.
> 
> 
> 
> I really appreciate your help with this!

Hmm. I looked into the code and verified that all the endpoints should be correct. What country are you in? Have you verified your vehicle is showing up on the official website (linked in the readme?)

**Comment by ckevac** [comment]
I'm in Canada and I just got off the phone with Chrysler. They said they have stopped using the Chrysler Connect site for vehicle control and that I have to use this site instead:  https://www.mopar.com/chrysler/en-ca/my-vehicle/dashboard.html#

Is it possible for your add-on to use that site for Canadian users?

**Comment by Blueion76** [comment]
> I'm in Canada and I just got off the phone with Chrysler. They said they have stopped using the Chrysler Connect site for vehicle control and that I have to use this site instead: https://www.mopar.com/chrysler/en-ca/my-vehicle/dashboard.html#
> 
> Is it possible for your add-on to use that site for Canadian users?

Unfortunately that site is entirely different in how it works. As of now, I'm not able to add support for that. Sorry :(

**Comment by ckevac** [comment]
That's ok. I appreciate the effort.  Thanks again.

**Comment by Wetzel402** [comment]
> 
> Look at the example here: https://github.com/Blueion76/FCAUconnect-HA/tree/master?tab=readme-ov-file#standalone-docker-container
> 
> Just tested this with my account and it seems to work fine.

For some reason the container doesn't obtain an IP address on my docker network.  Is there something special I need to do with your container? 

```
version: "3.9"                                                                                                                                     
services:
  FCAUconnect:
    image: ghcr.io/blueion76/image-amd64-fca-uconnect:latest 
    container_name: FCAUconnect
    hostname: FCAUconnect
    environment:
      - STANDALONE=True
      - FCAUconnect_FCAUser=""
      - FCAUconnect_FCAPw=""
      - FCAUconnect_FCAPin=
      - FCAUconnect_SupervisorToken=""
      - FCAUconnect_StartDelaySeconds=2
      - FCAUconnect_Region=America // Can be America, Europe, Asia or Canada
      - FCAUconnect_Brand=Chrysler // Can be Jeep, Fiat, Chrysler, Maserati, AlfaRomeo, Ram, or Dodge
      - FCAUconnect_MqttUser=""
      - FCAUconnect_MqttPw=""
      - FCAUconnect_MqttServer=10.10.0.102
      - FCAUconnect_MqttPort=1883
      - FCAUconnect_Debug=true // Can be set to false if not needed
      - FCAUconnect_RefreshInterval=2
      - FCAUconnect_AutoDeepRefresh=false
      - FCAUconnect_HomeAssistantUrl=http://10.10.0.99:8123
    networks:
      ha:
        ipv4_address: 10.10.0.107
networks:
  ha:
    external: true
```
